language: go

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

gobuild_args: -race

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/69b57e988266b7fa9abe
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false
